#!/usr/bin/env python

import sys

from tokenizer import tokenize
from parser import parse
from evaluator import evaluate

def repl(eval):
    environment = {}
    status = {
        "interactive":True,
        "force_interactive":False,
        "show_environment":False,
    }
    for arg in sys.argv[1:]:
        if not arg.startswith("-"):
            continue
        if arg == "-e":
            status["show_environment"] = True            

    while True:
        try:
            source_line = input("% ") 
            if source_line == ".e":
                status["show_environment"] = not status["show_environment"] 
                if status["show_environment"]:
                    print(environment)
                continue
            eval(source_line, environment) 
            if status["show_environment"]:
                print(environment)  
        except EOFError:
            print(" exiting.")
            exit(0)
        except KeyboardInterrupt:
            print(" exiting.")
            exit(0)

def eval(code, environment):
    tokens = tokenize(code)
    ast = parse(tokens)
    value, _ = evaluate(ast, environment)
    print(value)

if __name__ == "__main__":
    repl(eval)